### ISSUE TITLE
Add info about authors of river descriptions

### ISSUE THREAD

**Issue by sawickib** [czerwix/KajakOrg#3]
List of authors of Splywww at kajak.org.pl in years 2006-2022:
 - Andrzej <atomikpl>
 - Andrzej Galikowski
 - Andrzej Kadlec
 - Andrzej Łaptaś
 - Andrzej Łaptaś, Kraków
 - andy galikowski
 - ANIAK71@O2.PL
 - Anna Sawicka
 - Artur Maj oraz inni
 - Bartosz Sawicki 
 - Bogdan Rudnik
 - Bogdan Wojsa
 - drzazga przemek
 - Dworak H
 - Gimli1
 - GRUBY
 - *j
 - Janusz Filipecki (GRUBY)
 - Janusz Kulecki
 - Janusz Michalski (JaMi) 
 - jerzybart@...
 - Jolanta Loster
 - Krzysztof Hancewicz
 - Leszek Opyrchał
 - Łukasz Marcinkowski
 - Maciej Odrowąż-Mieszkowski
 - Maciej Urbaniak
 - Maciek Mieszkowski
 - Maciek Mieszkowski na podstawie informacji od "Adamus"
 - Maciek Mieszkowski na podstawie informacji od Janusza Kulińskiego 
 - Maciek Mieszkowski na podstawie informacji od (pseudonim - marianna)
 - Maciek Mieszkowski na podstawie informacji od Pawła 
 - Maciek Mieszkowski na podstawie informacji uzyskanych od "Sorpet" 
 - Marcin
 - Marcin Knyps
 - Marcin Mikulski
 - Marek Baranowski  
 - Marek Werner (marucha)
 - Marta Adamska i Maati
 - Paweł Woźniak
 - Paweł Zetkowski
 - piast 
 - Piotr Eichler z Suchego Lasu
 - Piotrek
 - Piotrek Knyps
 - Piotr Kaliszek
 - pjas (at) op.pl
 - Przewodnik_XL
 - Rafał Tomczyk
 - rrokicki
 - Sebastian -Gizbern- Lipiejko
 - Sebastian Lipiejko
 - Ślimak
 - Tomasz Toczyski
 - www.browarek.org.pl
 - yeti
 - Zbigniew Leszczyński

**Comment by czerwix** [comment]
Added to about screen. with the newest commits to the main change will be visible. in the future each author will be credited in Path's about screen(to be build)
